FROM python:3.12-slim

WORKDIR /web-service

RUN pip install uv

COPY pyproject.toml ./

RUN uv sync

COPY static ./static
COPY templates ./templates
COPY app.py .

#development mode
# CMD ["uv", "run", "--", "flask", "run", "-h", "0.0.0.0", "-p", "5000"]

#production mode
CMD ["uv", "run", "--", "gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]
